#!/usr/bin/env bash

jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.jsx\?$' | tr '\n' ' ')

if [ -z "$jsfiles" ]
then
  echo "💩  No staged files match \.jsx\?$"
  exit 0
fi

echo "✨  Running tasks for \.jsx\?$"

# Eslint all staged .js files
echo "✔︎ Running eslint"
echo "$jsfiles" | xargs eslint \
  --fix
[ $? != 0 ] && exit 1

# Prettify all staged .js files
echo "✔︎ Running prettier"
echo "$jsfiles" | xargs prettier \
  --print-width 120 \
  --single-quote \
  --trailing-comma es5 \
  --write
[ $? != 0 ] && exit 1

# Eslint all staged .js files again to override prettier output
echo "✔︎ Running eslint fixes"
echo "$jsfiles" | xargs eslint \
  --no-eslintrc \
  --env es6,node,mocha \
  --parser-options=ecmaVersion:2016 \
  --rule 'space-before-function-paren: [2, { "anonymous": "always", "named": "never", "asyncArrow": "always" }]' \
  --fix
[ $? != 0 ] && exit 1

# Add back the modified/prettified files to staging
echo "$jsfiles" | xargs git add
[ $? != 0 ] && exit 1

exit 0
