name: Tests and Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
# TODO Run our Node Security Scanner
#  security-scan:
#    runs-on: ubuntu-latest
#    steps:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion: [ 14, 16, 18, 20 ]
    name: Run Tests - Node ${{ matrix.nodeVersion }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
          check-latest: true
          cache: 'npm'
      - name: Run tests and collect coverage
        run: ./scripts/cibuild.sh
      - name: Upload coverage reports to Codecov
        # https://github.com/marketplace/actions/codecov
        uses: codecov/codecov-action@v3
